module.exports = {
  POSTS_RECEIVED: "POSTS_RECEIVED",
  POST_RECEIVED: "POST_RECEIVED",
  COMMENT_RECEIVED: "COMMENT_RECEIVED",
  COMMENT_REMOVED: "COMMENT_REMOVED",
  LIKE_RECEIVED: "LIKE_RECEIVED",
  LIKE_REMOVED: "LIKE_REMOVED",
  USER_POSTS_RECEIVED: "USER_POSTS_RECEIVED"
};
